import { useEffect, useRef, useState } from 'react'

const WHATSAPP = 'https://wa.me/923215504666'
const MAPS = 'https://maps.app.goo.gl/TnMwPty6edcxLTzv9?g_st=awb'
const wa = (message) => `${WHATSAPP}?text=${encodeURIComponent(message)}`

function Icon({ name, size = 24, stroke = 1.8 }) {
  const paths = {
    computer: <><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/></>, camera: <><path d="M4 7h3l1.5-2h7L17 7h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="3.5"/></>, printer: <><path d="M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v7H6z"/><path d="M18 12h.01"/></>, palette: <><path d="M12 3a9 9 0 1 0 0 18h1.1a1.9 1.9 0 0 0 0-3.8H12a1.7 1.7 0 0 1 0-3.4h1.5A6.5 6.5 0 0 0 12 3Z"/><circle cx="7.5" cy="10" r=".7" fill="currentColor"/><circle cx="9.5" cy="6.8" r=".7" fill="currentColor"/><circle cx="14" cy="6.8" r=".7" fill="currentColor"/></>, file: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/></>, id: <><rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8" cy="11" r="2"/><path d="M5.5 16c.6-1.6 1.5-2.4 2.5-2.4s1.9.8 2.5 2.4M13 10h5M13 14h5"/></>, keyboard: <><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 10h.01M10 10h.01M13 10h.01M16 10h.01M7 14h6M16 14h1"/></>, mobile: <><rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/></>, message: <><path d="M20 11.5a8.2 8.2 0 0 1-9.6 8.1L4 21l1.5-5.7A8.2 8.2 0 1 1 20 11.5Z"/><path d="M8.5 10.5c.4 2.2 2.3 4 4.5 4.5M9 8.5l1.2 1.7-1 1.1M14.5 14l1.4-1.1-1.7-1.1"/></>, map: <><path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3Z"/><path d="M9 3v15M15 6v15"/></>, pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>, phone: <><path d="M21 16.5v3a1.8 1.8 0 0 1-2 1.8A17.8 17.8 0 0 1 2.7 5 1.8 1.8 0 0 1 4.5 3h3a1.8 1.8 0 0 1 1.8 1.5l.5 2.6a1.8 1.8 0 0 1-.5 1.7L8.2 10a14.5 14.5 0 0 0 5.8 5.8l1.2-1.1a1.8 1.8 0 0 1 1.7-.5l2.6.5a1.8 1.8 0 0 1 1.5 1.8Z"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, chevron: <path d="m9 18 6-6-6-6"/>, menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, check: <path d="m5 12 4 4L19 6"/>, building: <><path d="M3 21h18M5 21V5l7-3v19M19 21V9l-7-2M8 7h1M8 11h1M8 15h1M15 12h1M15 16h1"/></>
  }
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={stroke} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

const services = [
  { id:'computer', icon:'computer', title:'Computer Services', desc:'Reliable computer support for everyday software, installation and troubleshooting needs.', highlights:['Windows Installation','Software Installation','Driver Installation','Computer Troubleshooting','Basic Hardware Service'], message:'Hello Best Computer, I need information about your Computer Services.' },
  { id:'photostudio', icon:'camera', title:'Photostudio', desc:'Professional photo services for personal, official and document requirements.', highlights:['Passport Size Photos','Visa / ID Photos','Photo Editing','Photo Printing','Photo Albums'], message:'Hello Best Computer, I need information about your Photostudio services.' },
  { id:'printing', icon:'printer', title:'Printing & Composing', desc:'Convenient printing, scanning, typing and document composing services.', highlights:['Black & White Printing','Color Printing','Scanning','Urdu Composing','English Typing','Document Formatting'], message:'Hello Best Computer, I need information about your Printing & Composing services.' },
  { id:'design', icon:'palette', title:'Graphic Design', desc:'Creative designs for personal, business and promotional needs.', highlights:['Business Cards','Flyers','Posters','Banners','Invitations','Social Media Designs'], message:'Hello Best Computer, I need information about your Graphic Design services.' },
  { id:'stamp', icon:'file', title:'Stamp Paper', eyebrow:'Stamp Paper & Documentation Assistance', desc:'Stamp paper and document preparation assistance for everyday documentation needs.', highlights:['Stamp Paper Assistance','Document Preparation','Agreement Composing','Application Composing','Document Printing'], message:'Hello Best Computer, I need information about your Stamp Paper services.' },
  { id:'sahulat', icon:'id', title:'NADRA / E-Sahulat', desc:'NADRA / E-Sahulat related facilitation services available at our center.', highlights:['Related Facilitation','Information at Our Center','Document Assistance','Service Guidance'], message:'Hello Best Computer, I need information about your NADRA / E-Sahulat related services.' },
  { id:'computer-accessories', icon:'keyboard', title:'Computer Accessories', desc:'Essential accessories and everyday computer-use products.', highlights:['Keyboard','Mouse','USB','Cables','Chargers','Memory Cards','Basic Accessories'], message:'Hello Best Computer, I want information about your Computer Accessories.' },
  { id:'mobile-accessories', icon:'mobile', title:'Mobile Accessories', desc:'Useful mobile accessories for everyday use.', highlights:['Chargers','Data Cables','Handsfree','Earphones','Power Banks','Mobile Holders','Memory Cards'], message:'Hello Best Computer, I want information about your Mobile Accessories.' },
]

const nav = [
  { label: 'Home', link: '/#home' },
  { label: 'Services', link: '/#services' },
  { label: 'Online Tools ▼', link: '/tools.html' },
  { label: 'AI Photo Studio ✨', link: '/ai-studio.html' },
  { label: 'Photostudio', link: '/#photostudio' },
  { label: 'Printing & Composing', link: '/#printing' },
  { label: 'Graphic Design', link: '/#design' },
  { label: 'Location', link: '/#location' },
  { label: 'Contact', link: '/#contact' }
];

function Brand() { return <a href="/#home" className="brand" aria-label="Best Computer home"><span className="brand-mark"><Icon name="computer" size={19}/></span><span>BEST <b>COMPUTER</b><small>Digital service center</small></span></a> }
function WAButton({ children='Chat on WhatsApp', message, className='' }) { return <a className={`button button-wa ${className}`} href={wa(message || 'Hello Best Computer, I would like to know about your services.')} target="_blank" rel="noreferrer"><Icon name="message" size={19}/>{children}</a> }

function Header() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [adminOpen, setAdminOpen] = useState(false)
  useEffect(() => { const fn=()=>setScrolled(window.scrollY>12); addEventListener('scroll',fn,{passive:true}); return()=>removeEventListener('scroll',fn) }, [])
  const jump = () => setOpen(false)
  return <header className={`header ${scrolled?'scrolled':''}`}><div className="nav-wrap"><Brand/>
    <nav className="desktop-nav">
      {nav.map(item=><a href={item.link} key={item.label}>{item.label}</a>)}
    </nav>
    <div className="nav-actions"><button className="admin-signin" onClick={()=>setAdminOpen(true)}>Admin Sign In</button><WAButton className="nav-wa"/><a className="mobile-wa" href={wa('Hello Best Computer, I would like to know about your services.')} aria-label="Chat on WhatsApp" target="_blank" rel="noreferrer"><Icon name="message"/></a><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open?'Close menu':'Open menu'}><Icon name={open?'close':'menu'}/></button></div></div>
  <div className={`mobile-menu ${open?'open':''}`} id="mobile-menu">{nav.map(item=><a href={item.link} onClick={jump} key={item.label}>{item.label}<Icon name="chevron" size={16}/></a>)}<button className="admin-signin mobile-admin" onClick={()=>{setOpen(false);setAdminOpen(true)}}>Admin Sign In</button><WAButton className="mobile-menu-wa"/></div>
  {adminOpen&&<div className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="admin-title" onMouseDown={()=>setAdminOpen(false)}><form className="admin-card" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>e.preventDefault()}><button className="admin-close" type="button" onClick={()=>setAdminOpen(false)} aria-label="Close admin sign in"><Icon name="close" size={19}/></button><p>Best Computer</p><h2 id="admin-title">Admin Sign In</h2><label>Email or username<input type="text" autoComplete="username" placeholder="Enter your username"/></label><label>Password<input type="password" autoComplete="current-password" placeholder="Enter your password"/></label><button className="admin-submit" type="submit">Sign In</button></form></div>}</header>
}

function Showcase() {
  const [active,setActive]=useState(0); const [paused,setPaused]=useState(false); const touch=useRef(null); const count=services.length
  const change=(dir)=>setActive(x=>(x+dir+count)%count)
  useEffect(()=>{if(paused) return; const timer=setInterval(()=>change(1),4500); return()=>clearInterval(timer)},[paused])
  return <div className="showcase" role="region" aria-roledescription="carousel" aria-label="Featured services" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current===null)return; const delta=e.changedTouches[0].clientX-touch.current; if(Math.abs(delta)>40)change(delta>0?-1:1); touch.current=null}}>
    <div className="showcase-top"><span className="showcase-label">Featured services</span><span className="showcase-count">{String(active+1).padStart(2,'0')} <i/> {String(count).padStart(2,'0')}</span></div>
    <div className="slides">{services.map((s,i)=><article className={`slide ${i===active?'active':''}`} key={s.id} aria-hidden={i!==active}><div className="slide-orbit orbit-a"/><div className="slide-orbit orbit-b"/><div className="slide-icon"><Icon name={s.icon} size={45}/></div><div className="slide-content"><p>Best Computer offers</p><h2>{s.title}</h2><span>{s.desc}</span><div className="slide-tags">{s.highlights.slice(0,3).map(x=><em key={x}>{x}</em>)}</div><a href={wa(s.message)} target="_blank" rel="noreferrer" tabIndex={i===active?0:-1}>Ask on WhatsApp <Icon name="arrow" size={16}/></a></div></article>)}</div>
    <div className="showcase-footer"><div className="slider-dots" role="tablist" aria-label="Choose service slide">{services.map((s,i)=><button key={s.id} className={i===active?'selected':''} onClick={()=>setActive(i)} aria-label={`Show ${s.title}`} aria-selected={i===active} role="tab"/>)}</div><div className="slider-controls"><button onClick={()=>change(-1)} aria-label="Previous service"><Icon name="chevron" size={18}/></button><button onClick={()=>change(1)} aria-label="Next service"><Icon name="chevron" size={18}/></button></div></div>
  </div>
}

function Hero(){return <section className="hero" id="home"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><span/>Your local digital service center</p><h1>Your <strong>One-Stop Destination</strong> for Computer, Digital, Printing &amp; Photostudio Services</h1><p className="hero-text">Professional computer services, photostudio, printing, composing, graphic design, documentation and accessories — conveniently available at Best Computer.</p><div className="hero-buttons"><WAButton/><a className="button button-secondary" href={MAPS} target="_blank" rel="noreferrer"><Icon name="pin" size={19}/>Get Directions</a></div><ul className="trust-points">{['Multiple Services Under One Roof','Professional & Convenient Service','Easy WhatsApp Contact','Local Customer Support'].map(x=><li key={x}><span><Icon name="check" size={14}/></span>{x}</li>)}</ul></div><Showcase/></div></section>}

function ServiceCard({s}){return <article className="service-card" id={s.id}><div className="service-icon"><Icon name={s.icon}/></div>{s.eyebrow&&<p className="card-eyebrow">{s.eyebrow}</p>}<h3>{s.title}</h3><p>{s.desc}</p><ul>{s.highlights.map(x=><li key={x}><Icon name="check" size={14}/>{x}</li>)}</ul><a href={wa(s.message)} target="_blank" rel="noreferrer">Ask on WhatsApp <Icon name="arrow" size={16}/></a></article>}
function Services(){return <section className="section services" id="services"><div className="section-heading"><p className="eyebrow"><span/>What we do</p><h2>Our Services</h2><p>Everything you need for your computer, digital, printing and photostudio needs — all in one place.</p></div><div className="services-grid">{services.map(s=><ServiceCard key={s.id} s={s}/>)}</div></section>}

function Why(){const features=[['building','Multiple Services','Many everyday digital and computer services available in one place.'],['check','Convenient Service','Simple and convenient service for local customers.'],['message','Easy WhatsApp Contact','Contact us directly through WhatsApp.'],['pin','Local Support','Visit our shop or contact us for assistance.']]; return <section className="section why"><div className="why-intro"><p className="eyebrow"><span/>Why us</p><h2>Why Choose<br/><em>Best Computer?</em></h2><p>A convenient place for your everyday computer, digital, printing and photostudio needs.</p><a href="#location" className="text-link">Find our location <Icon name="arrow" size={16}/></a></div><div className="why-grid">{features.map(([i,t,d])=><article key={t}><div><Icon name={i}/></div><h3>{t}</h3><p>{d}</p></article>)}</div></section>}

function Location(){return <section className="section location" id="location"><div className="location-map" aria-label="Map illustration showing the Best Computer location"><div className="map-grid"/><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-pin"><span><Icon name="pin" size={26}/></span><b>BEST<br/>COMPUTER</b></div><div className="map-label one">Peshawar Road</div><div className="map-label two">Dhok Mustaqeem</div></div><div className="location-copy"><p className="eyebrow"><span/>Find us easily</p><h2>Visit Best<br/><em>Computer</em></h2><p>Looking for Best Computer? Get directions to our shop on Google Maps.</p><div className="address"><div><Icon name="pin"/></div><span><small>OUR LOCATION</small>Dhok Mustaqeem, Peshawar Road, Rawalpindi</span></div><a className="button button-dark" href={MAPS} target="_blank" rel="noreferrer"><Icon name="map" size={19}/>Get Directions</a></div></section>}

function Contact(){return <section className="contact" id="contact"><div><p className="eyebrow"><span/>Quick and easy contact</p><h2>Need a Service?<br/><em>Let's Talk on WhatsApp.</em></h2><p>Send us your requirement and we'll guide you about the service.</p></div><div className="contact-action"><WAButton className="large-wa"/><a href="tel:+923215504666" className="phone-link"><Icon name="phone" size={18}/><span>Or call us at <b>+92 321 5504666</b></span></a></div></section>}
function Footer(){return <footer><div className="footer-main"><div className="footer-brand"><Brand/><p>Computer, Digital &amp; Photostudio Services Under One Roof.</p><WAButton/></div><div><h3>Quick Links</h3>{nav.map(item=><a href={item.link} key={item.label}>{item.label}</a>)}</div><div><h3>Services</h3>{services.map(s=><a href={`/#${s.id}`} key={s.id}>{s.title}</a>)}</div><div className="footer-contact"><h3>Contact</h3><a href={WHATSAPP} target="_blank" rel="noreferrer"><Icon name="message" size={17}/>+92 321 5504666</a><a href={MAPS} target="_blank" rel="noreferrer"><Icon name="pin" size={17}/>Dhok Mustaqeem,<br/> Peshawar Road, Rawalpindi</a></div></div><div className="footer-bottom">© 2026 Best Computer. All Rights Reserved.<a href="/#home">Back to top <Icon name="arrow" size={15}/></a></div></footer>}
function BottomActions(){return <><a className="floating-wa" href={wa('Hello Best Computer, I would like to know about your services.')} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><Icon name="message" size={26}/><span>Chat with us</span></a><div className="bottom-actions"><a href="tel:+923215504666"><Icon name="phone"/>Call</a><a href={WHATSAPP} target="_blank" rel="noreferrer"><Icon name="message"/>WhatsApp</a><a href={MAPS} target="_blank" rel="noreferrer"><Icon name="map"/>Directions</a></div></>}
export default function App(){return <><Header/><main><Hero/><Services/><Why/><Location/><Contact/></main><Footer/><BottomActions/></>}
